// Code generated by "stringer --type DataType"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAW-1]
	_ = x[CRED-2]
	_ = x[FILE-3]
	_ = x[CARD-4]
}

const _DataType_name = "RAWCREDFILECARD"

var _DataType_index = [...]uint8{0, 3, 7, 11, 15}

func (i DataType) String() string {
	i -= 1
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
